<!-- Modal for User update -->
<div class="modal fade" id="zadankyModal" tabindex="-1" role="dialog" aria-hidden="true" data-dismiss="modal">
<div class="modal-dialog hugeModal modal-lg">
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title" id="exampleModalLongTitle">Náhled a úprava žádanky</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <div id="dynamicZadankyEditFormHere"></div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Zavřít</button>
        </div>
    </div>
</div>
</div>