<div class="row">
    <div class="col-lg-12 col-md-12">
        <div class="card">
            <div class="card-header card-header-danger card-header-icon">
                <div class="card-icon">
                    <i class="material-icons">business</i>
                </div>
                <div class="row">
                    <h4 class="card-title"> Správa číselníku firem</h4>
                    <a href="nastaveni-firma.php" class="btn btn-primary ml-auto mt-3"><i class="fa fa-plus"></i>  Přidat novou firmu</a>
                </div>
            </div>
            <div class="card-body">
                <?php getCompaniesTable(); ?>
            </div>
            <div class="card-footer">

            </div>
        </div>
    </div>
</div>