<div class="row">
    <div class="col-lg-12 col-md-12">
        <div class="card">
            <div class="card-header card-header-danger card-header-icon">
                <div class="card-icon">
                    <i class="material-icons">business</i>
                </div>
                <div class="row">
                    <h4 class="card-title">Přehled vah priorit dle typu projektu</h4>
                </div>
            </div>
            <div class="card-body">
                <?php getPrioritiesWeights(); ?>
            </div>
            <div class="card-footer">

            </div>
        </div>
    </div>
</div>