<!--   Core JS Files   -->




<!--<script src="dashboard/assets/js/plugins/perfect-scrollbar.jquery.min.js"></script> -->

<!--  Google Maps Plugin  -->
<script src="https://api.mapy.cz/loader.js"></script>

<!--  Google Maps Plugin  -->
<!--  <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB2Yno10-YTnLjjn_Vtk0V8cdcY5lC4plU"></script> -->


<!--  Plugin for Date Time Picker and Full Calendar Plugin  -->
<script src="/vip/dashboard/assets/js/plugins/moment.min.js"></script>

<!--	Plugin for the Datepicker, full documentation here: https://github.com/Eonasdan/bootstrap-datetimepicker -->
<script src="/vip/dashboard/assets/js/plugins/bootstrap-datetimepicker.min.js"></script>

<!--	Plugin for the Sliders, full documentation here: https://refreshless.com/nouislider/ -->
<script src="/vip/dashboard/assets/js/plugins/nouislider.min.js"></script>



<!--	Plugin for Select, full documentation here: https://silviomoreto.github.io/bootstrap-select -->

<!--	Plugin for Tags, full documentation here: https://xoxco.com/projects/code/tagsinput/  -->
<script src="/vip/dashboard/assets/js/plugins/bootstrap-tagsinput.js"></script>

<!--	Plugin for Fileupload, full documentation here: https://www.jasny.net/bootstrap/javascript/#fileinput -->
<script src="/vip/dashboard/assets/js/plugins/jasny-bootstrap.min.js"></script>

<!-- Plugins for presentation and navigation  -->
<script src="/vip/dashboard/assets/assets-for-demo/js/modernizr.js"></script>

<!-- Plugins for presentation and navigation  -->
<script src="/vip/dashboard/assets/js/plugins/select2/dist/js/select2.min.js"></script>
<script src="/vip/dashboard/assets/js/plugins/select2/dist/js/i18n/cs.js"></script>


<!-- Material Kit Core initialisations of plugins and Bootstrap Material Design Library -->

<script src="/vip/dashboard/assets/js/material-dashboard.js?v=2.0.2"></script>



<!-- Include a polyfill for ES6 Promises (optional) for IE11, UC Browser and Android browser support SweetAlert -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/core-js/2.4.1/core.js"></script>
<script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.5/dist/jquery.validate.min.js"></script>



<!-- Library for adding dinamically elements -->
<script src="/vip/dashboard/assets/js/plugins/arrive.min.js"></script>

<!-- Forms Validations Plugin -->
<script src="/vip/dashboard/assets/js/plugins/jquery.validate.min.js"></script>
<script src="/vip/dashboard/assets/js/plugins/validate/pattern.js"></script>

<!--  Charts Plugin, full documentation here: https://gionkunz.github.io/chartist-js/ -->
<script src="/vip/dashboard/assets/js/plugins/chartist.min.js"></script>
<!-- -->

<script src="/vip/dashboard/assets/js/plugins/chartist-plugin-tooltip.min.js"></script>
<script src="/vip/dashboard/assets/js/plugins/chartist-plugin-pointlabels.min.js"></script>

<!--  Plugin for the Wizard, full documentation here: https://github.com/VinceG/twitter-bootstrap-wizard -->
<script src="/vip/dashboard/assets/js/plugins/jquery.bootstrap-wizard.js"></script>

<!--  Notifications Plugin, full documentation here: https://bootstrap-notify.remabledesigns.com/    -->
<script src="/vip/dashboard/assets/js/plugins/bootstrap-notify.js"></script>

<!-- Vector Map plugin, full documentation here: https://jvectormap.com/documentation/ -->
<script src="/vip/dashboard/assets/js/plugins/jquery-jvectormap.js"></script>

<!-- Sliders Plugin, full documentation here: https://refreshless.com/nouislider/ -->
<script src="/vip/dashboard/assets/js/plugins/nouislider.min.js"></script>

<!--  Plugin for Select, full documentation here: https://silviomoreto.github.io/bootstrap-select -->
<script src="/vip/dashboard/assets/js/plugins/jquery.select-bootstrap.js"></script>

<!--  DataTables.net Plugin, full documentation here: https://datatables.net/    -->
<script src="/vip/dashboard/assets/js/plugins/jquery.datatables.js"></script>
<script src="/vip/dashboard/assets/js/plugins/dataTables.responsive.min.js"></script>

<!-- Sweet Alert 2 plugin, full documentation here: https://limonte.github.io/sweetalert2/ -->
<script src="/vip/dashboard/assets/js/plugins/sweetalert2.js"></script>

<!-- Plugin for Fileupload, full documentation here: https://www.jasny.net/bootstrap/javascript/#fileinput -->
<script src="/vip/dashboard/assets/js/plugins/jasny-bootstrap.min.js"></script>



<!--  Full Calendar Plugin, full documentation here: https://github.com/fullcalendar/fullcalendar    -->
<script src="dashboard/assets/js/plugins/fullcalendar-3.9.0/fullcalendar.min.js"></script>
<script src='dashboard/assets/js/plugins/fullcalendar-3.9.0/locale/cs.js'></script>

<!-- dropzone -->
<script src="../js/dropzone5.9.3.min.js"></script>

<!-- PDFObject -->
<script src="../js/pdfobject.min.js"></script>

<!-- Bootstrap Autocomplete -->
<script src="https://cdn.jsdelivr.net/gh/xcash/bootstrap-autocomplete@v2.3.7/dist/latest/bootstrap-autocomplete.min.js"></script>

<!-- demo init
<script src="dashboard/assets/js/plugins/demo.js"></script>
<script src="dashboard/assets/js/plugins/jquery.session.js"></script>
-->
<script src="https://cdn.tiny.cloud/1/71hu3pu3otavwtctqjgkbcdrsrcwqw5kqok9bsz308yom17q/tinymce/5/tinymce.min.js"></script>

<script src="/js/URI.js"></script>
<script src="/js/functions.js"></script>
<script src="/js/requestModal.js"></script>

<!-- FormBuilder -->
<!-- <script src="https://formbuilder.online/assets/js/form-render.min.js"></script> -->
<!-- <script src="https://formbuilder.online/assets/js/form-builder.min.js"></script> -->

<!-- HTMX -->
<!-- <script src="https://unpkg.com/htmx.org@1.9.11" integrity="sha384-0gxUXCCR8yv9FM2b+U3FDbsKthCI66oH5IA9fHppQq9DDMHuMauqq1ZHBpJxQ0J0" crossorigin="anonymous"></script> -->

<!-- MAPY - leaflet -->
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
        integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo="
        crossorigin=""></script>

<script type="text/javascript">Loader.load()</script>
